language: android

jdk: openjdk7

android:
  components:
    - build-tools-23.0.1
    - android-23
    - sys-img-x86-android-23
    - extra-google-m2repository
    - extra-android-m2repository

script: ./gradlew test

deploy:
  provider: script
  script: ./gradlew uploadDebugToHockeyApp
  on:
    branch: master


# Slack Notification
notifications:
  slack: kotlinchina:dQzkeJ1Fwf9yMsAnTB7zv2yF
